# Generated by Django 5.0.1 on 2025-02-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.order'),
            preserve_default=False,
        ),
    ]
