# Generated by Django 5.0.1 on 2025-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
