# Generated by Django 5.0.1 on 2025-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[("men's clothing", "Men's Clothing"), ("women's clothing", "Women's Clothing")], max_length=30),
        ),
    ]
