# Generated by Django 5.0.1 on 2025-01-29 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_by_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 15, 49, 27, 268482)),
        ),
    ]
