# Generated by Django 5.0.1 on 2025-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
