# Generated by Django 5.0.1 on 2025-01-30 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
